server.port=8080
server.address=0.0.0.0

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.console-url=${MINIO_CONSOLE_URL:http://localhost:9001}

# H2
spring.datasource.url=jdbc:h2:mem:filehost
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

spring.docker.compose.enabled=false