spring.application.name=fileHost
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=GG_ggh8
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mietfilehost
server.port=8443

server.http.port=8080

minio.url=http://localhost:9000
minio.console-url=http://localhost:9001
minio.access-key=minioadmin
minio.secret-key=minioadmin